# -*- coding: utf-8 -*-
"""Bayesian_Approach_to_Model_Selection_in_Clustering_Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kt-YSj5rmvpfejS7fehxZPzt_8Wf4ckG

# Evaluation Object
"""

#Expected Variables are numerical
def compute_penalized_posterior(X_scaled, Z, means, sigma2=1.0, prior_type="bic"):
    N, p = X_scaled.shape
    K = means.shape[0]

    # 1. Standard Gaussian Log-Likelihood
    assigned_means = means[Z]
    sq_err = np.sum((X_scaled - assigned_means) ** 2)
    log_likelihood = N * (-0.5 * p * np.log(2 * np.pi * sigma2)) - (1.0 / (2.0 * sigma2)) * sq_err

    # 2. Prior Penalty on K
    if prior_type == "bic":
        # Penalize K * p parameters
        log_prior = -0.5 * (K * p) * np.log(N)
    elif prior_type == "gaussian_means":
        # Prior: mu_k ~ N(0, 10^2)
        sigma02 = 100.0
        log_prior = -0.5 * K * p * np.log(2 * np.pi * sigma02) - np.sum(means**2) / (2 * sigma02)
    else:
        log_prior = 0.0  # Raw unpenalized (will overfit)

    return log_likelihood, log_prior, log_likelihood + log_prior